[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_name = "emily-de300"
db_connection = "postgres_de_course"
db_alchemy_driver = "postgresql+psycopg2"

[files]
sftp_connection = "sftp_tiger"
s3_bucket = "de300spring2024-emilykohlberg"
s3_file_key = "wine.csv"
remote_file = "de300-data/wine.csv"
local_file = "./data/wine.csv"

[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "quality"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95
