[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_identifier = "emily-de300"
db_connection = "emily-de300-hw4"
username = 'postgres'
password = 'emily123'
host = 'emily-de300.cvwhaidrmrqj.us-east-2.rds.amazonaws.com'
port = '5432'  # Default port for PostgreSQL
default_db = 'postgres'  # Default database you can connect to
db_name = 'hw4'
db_alchemy_driver = "postgresql+psycopg2"

[files]
s3_bucket = "de300spring2024-emilykohlberg"
s3_file_key = "heart_disease.csv"
remote_file = "heart_disease.csv"
local_file = "heart_disease.csv"

[spark]
number_of_folds = 5
split_seed = 7576
train_test_split = 0.9
labels = "target"

[sklearn]
train_test_ratio = 0.1
labels = "target"



[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "Wine"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95